### ISSUE TITLE
So how do you use this client side?

### ISSUE THREAD

**Issue by tohagan** [nolanlawson/pouchdb-all-dbs#21]
Sorry I'm using Angular and don't have `require()`.
So how do I register this plugin?  
I expected something like `PouchDB.plugin(DropAll);`
But what don't see a `$window.DropAll` (or similar) declared to do this.

Following your README instructions I find PouchDB.allDbs is undefined.

**Comment by nolanlawson** [comment]
If you are using `script` tags, then you need to attach `PouchDB` to the `window` object before using. Otherwise if you are using Browserify/webpack/etc. then you can do `require('pouchdb').plugin(require('pouchdb-all-dbs'))`. Sorry it's not any easier.

**Comment by tohagan** [comment]
Unfortunately I'm using Angular which does not have require() defined AFAIK.  I eventually avoided using this API by tracking db's I've created/removed another way - sample concept tho. Thanks for the idea.

**Comment by nolanlawson** [comment]
Sorry about that! In the future please know that you can always convert from require/Browserify/Webpack Land into Script Land by using a tool like wzrd.in. E.g.: http://wzrd.in/standalone/pouchdb-all-dbs

Then you just take that script, and you now have a global `window.pouchdbAllDbs` object, which you can attach to PouchDB using `PouchDB.plugin(pouchdbAllDbs)`. Hope that helps!
