### ISSUE TITLE
Incompatibility with PouchDB 5.4.X

### ISSUE THREAD

**Issue by bedney** [nolanlawson/pouchdb-all-dbs#22]
Because of the deprecation of PouchDB.utils, I now get this error when running this plugin with PouchDB 5.4.3:

`TypeError: undefined is not an object (evaluating 'window.PouchDB.utils.Promise')...`

I'd be happy to submit a PR, but I wasn't sure which way you wanted to jump on it.

**Comment by nolanlawson** [comment]
I'm looking at this; thanks for reporting.

**Comment by nolanlawson** [comment]
working on it: https://github.com/nolanlawson/pouchdb-all-dbs/pull/23

**Comment by bedney** [comment]
Great! Thanks Nolan (and thanks for all of your hard work on PouchDB - it's really awesome).

**Comment by nolanlawson** [comment]
no prob. fixed in #23, will release a patch version now

**Comment by nolanlawson** [comment]
1.0.2 released

**Comment by bedney** [comment]
Thank you sir! I really appreciate it!
